<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260910181837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE arrendatario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rut VARCHAR(12) NOT NULL, nombre VARCHAR(150) NOT NULL, giro VARCHAR(80) NOT NULL, direccion VARCHAR(120) NOT NULL, comuna VARCHAR(50) NOT NULL, ciudad VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE empresa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rut VARCHAR(12) NOT NULL, razon_social VARCHAR(150) NOT NULL, giro VARCHAR(80) NOT NULL, direccion VARCHAR(120) NOT NULL, comuna VARCHAR(50) NOT NULL, ciudad VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE factura (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periodo VARCHAR(7) NOT NULL, folio INT NOT NULL, tipo_dte INT NOT NULL, fecha_emision DATE NOT NULL, neto INT NOT NULL, iva INT NOT NULL, exento INT NOT NULL, total INT NOT NULL, archivo_plano TEXT NOT NULL, empresa_id INT NOT NULL, arrendatario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9EBA009521E1991 ON factura (empresa_id)');
        $this->addSql('CREATE INDEX IDX_F9EBA009F1AE2EBA ON factura (arrendatario_id)');
        $this->addSql('CREATE TABLE factura_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion VARCHAR(180) NOT NULL, monto INT NOT NULL, factura_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_628C4BC4F04F795F ON factura_item (factura_id)');
        $this->addSql('CREATE TABLE liquidacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periodo VARCHAR(7) NOT NULL, estado VARCHAR(20) NOT NULL, total INT NOT NULL, propiedad_id INT NOT NULL, factura_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_10305B3925C78794 ON liquidacion (propiedad_id)');
        $this->addSql('CREATE INDEX IDX_10305B39F04F795F ON liquidacion (factura_id)');
        $this->addSql('CREATE TABLE liquidacion_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(20) NOT NULL, descripcion VARCHAR(180) NOT NULL, monto INT NOT NULL, liquidacion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9CAAF090326DAF0C ON liquidacion_item (liquidacion_id)');
        $this->addSql('CREATE TABLE propiedad (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(150) NOT NULL, direccion VARCHAR(180) NOT NULL, empresa_id INT NOT NULL, arrendatario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6F3EFE0D521E1991 ON propiedad (empresa_id)');
        $this->addSql('CREATE INDEX IDX_6F3EFE0DF1AE2EBA ON propiedad (arrendatario_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009F1AE2EBA FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE factura_item ADD CONSTRAINT FK_628C4BC4F04F795F FOREIGN KEY (factura_id) REFERENCES factura (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liquidacion ADD CONSTRAINT FK_10305B3925C78794 FOREIGN KEY (propiedad_id) REFERENCES propiedad (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liquidacion ADD CONSTRAINT FK_10305B39F04F795F FOREIGN KEY (factura_id) REFERENCES factura (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liquidacion_item ADD CONSTRAINT FK_9CAAF090326DAF0C FOREIGN KEY (liquidacion_id) REFERENCES liquidacion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE propiedad ADD CONSTRAINT FK_6F3EFE0D521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE propiedad ADD CONSTRAINT FK_6F3EFE0DF1AE2EBA FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE factura DROP CONSTRAINT FK_F9EBA009521E1991');
        $this->addSql('ALTER TABLE factura DROP CONSTRAINT FK_F9EBA009F1AE2EBA');
        $this->addSql('ALTER TABLE factura_item DROP CONSTRAINT FK_628C4BC4F04F795F');
        $this->addSql('ALTER TABLE liquidacion DROP CONSTRAINT FK_10305B3925C78794');
        $this->addSql('ALTER TABLE liquidacion DROP CONSTRAINT FK_10305B39F04F795F');
        $this->addSql('ALTER TABLE liquidacion_item DROP CONSTRAINT FK_9CAAF090326DAF0C');
        $this->addSql('ALTER TABLE propiedad DROP CONSTRAINT FK_6F3EFE0D521E1991');
        $this->addSql('ALTER TABLE propiedad DROP CONSTRAINT FK_6F3EFE0DF1AE2EBA');
        $this->addSql('DROP TABLE arrendatario');
        $this->addSql('DROP TABLE empresa');
        $this->addSql('DROP TABLE factura');
        $this->addSql('DROP TABLE factura_item');
        $this->addSql('DROP TABLE liquidacion');
        $this->addSql('DROP TABLE liquidacion_item');
        $this->addSql('DROP TABLE propiedad');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
